name: Build

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Test
        run: dotnet test --no-build --configuration Release --verbosity normal
      - name: Pack
        run: dotnet pack **/DaeNe.AspNetCore.Conventions.csproj --configuration Release
      - name: Upload a publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: nuget
          path: '**/bin/Release/*.nupkg'
          retention-days: 7
          if-no-files-found: error
