name: CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
  
  publish:
    needs: build
    uses: ./.github/workflows/publish.yml
